blank_issues_enabled: false
contact_links:
  - name: DyneMCP Documentation
    url: https://github.com/davidnazareno/dynemcp#readme
    about: Check our documentation before creating an issue
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here
