name: Canary Release

on:
  push:
    branches-ignore:
      - main
      - develop
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/release-canary.yml'

# Explicitly define permissions needed for this workflow
permissions:
  contents: write # Needed for pushing commits and tags
  pull-requests: write # If you want to allow PR creation
  id-token: write # Needed for OIDC token authentication with npm

jobs:
  canary-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.8.0
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Build packages
        run: pnpm run build
        
      - name: Run tests
        run: pnpm run test
        
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Generate canary version
        run: pnpm run version
        env:
          RELEASE_TYPE: canary
          
      # Configuración segura para publicación en npm
      - name: Publish canary packages
        run: pnpm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          RELEASE_TYPE: canary
          # Aseguramos que los logs no muestren el token
          NPM_CONFIG_LOGLEVEL: error
